[package]
name = "love_bot_library"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
cmd_lib = "1.9.5"
env_logger = "0.11.6"
libc = "0.2.169"
log = "0.4.25"
ron = "0.8.1"
serde = { version="1.0.217", features = ["derive"]}
xcap = "0.3.1"
